name: Genera sito statico

on:
  # Esegue il workflow ogni volta che c'è un push sul branch main
  push:
    branches:
      - main
  # Esegue il workflow anche periodicamente (ogni ora, modificabile se necessario)
  schedule:
    - cron: "0 * * * *"  # Ogni ora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Installa eventuali dipendenze
        run: |
          python -m pip install --upgrade pip
          # Se il tuo script necessita di librerie aggiuntive, aggiungile qui, ad esempio:
          # pip install -r requirements.txt

      - name: Genera sito statico
        run: python site.py

      - name: Commit e push dei cambiamenti
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html
          # Verifica se ci sono modifiche; se sì, committa e pusha
          if ! git diff-index --quiet HEAD; then
            git commit -m "Aggiornamento sito statico"
            git push
          else
            echo "Nessun cambiamento rilevato."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
